@php
$saved = $workflow->exists ? $workflow->levels->map(fn($l) => ['id'=>$l->id,'name'=>$l->name,'approver_type'=>$l->approver_type,'approver_role'=>$l->approver_role,'user_ids'=>$l->selectedUsers->pluck('user_id')->all(),'rejection_comment_required'=>$l->rejection_comment_required])->all() : [];
$levelInputs = old('levels', $saved ?: [['name'=>'','approver_type'=>'supervisor','approver_role'=>null,'user_ids'=>[],'rejection_comment_required'=>true]]);
@endphp
<div class="qnox-workflows">@include('workflows::settings._shell')
<h1>{{ $workflow->exists ? 'Edit' : 'Create' }} {{ $moduleLabel }} workflow</h1>
<form method="post" action="{{ $workflow->exists ? route(config('workflows.routes.web.name_prefix', 'workflows.').'definitions.update', $workflow) : route(config('workflows.routes.web.name_prefix', 'workflows.').'definitions.store') }}" id="workflow-form">
@csrf @if($workflow->exists) @method('PUT') @endif
<input type="hidden" name="module_key" value="{{ old('module_key', $workflow->module_key) }}">
<input type="hidden" name="confirm_reorder" id="confirm-reorder" value="0">
<div class="card"><label for="workflow-name">Workflow name</label><input id="workflow-name" name="name" value="{{ old('name', $workflow->name) }}" required>@error('name')<span class="error">{{ $message }}</span>@enderror
<label>Module</label><input value="{{ $moduleLabel }}" readonly aria-readonly="true">
<label><input style="width:auto" type="checkbox" name="is_active" value="1" @checked(old('is_active', $workflow->is_active ?? true))> Active</label></div>
<div id="levels">
@foreach($levelInputs as $i => $level)<section class="card level" data-index="{{ $i }}"><div class="row"><h2>Level <span class="level-number">{{ $i+1 }}</span></h2><div><button type="button" class="secondary up">Move up</button> <button type="button" class="secondary down">Move down</button> <button type="button" class="danger remove">Remove</button></div></div>
@if(!empty($level['id']))<input type="hidden" data-field="id" name="levels[{{ $i }}][id]" value="{{ $level['id'] }}">@endif
<label>Name<input data-field="name" name="levels[{{ $i }}][name]" value="{{ $level['name'] ?? '' }}" required></label>@error("levels.$i.name")<span class="error">{{ $message }}</span>@enderror
<label>Approver<select data-field="approver_type" name="levels[{{ $i }}][approver_type]" class="approver-type"><option value="supervisor" @selected(($level['approver_type']??'')==='supervisor')>Employee supervisor</option><option value="role" @selected(($level['approver_type']??'')==='role')>Role</option><option value="users" @selected(($level['approver_type']??'')==='users')>Selected employees</option></select></label>
<p class="muted supervisor-help">The applicant's eligible supervisor is resolved when this level is reached.</p>
<label class="role-field">Role<select data-field="approver_role" name="levels[{{ $i }}][approver_role]"><option value="">Select a role</option>@foreach($roles as $role)<option value="{{ $role['value'] }}" @selected((string)($level['approver_role']??'')===(string)$role['value'])>{{ $role['label'] }}</option>@endforeach</select></label>@error("levels.$i.approver_role")<span class="error">{{ $message }}</span>@enderror
<label class="users-field">Employees<input class="user-search" type="search" placeholder="Search employees" aria-label="Search employees"><select data-field="user_ids" name="levels[{{ $i }}][user_ids][]" multiple size="6" aria-label="Employee selection">@foreach($users as $user)<option value="{{ $user['value'] }}" @selected(in_array((string)$user['value'],array_map('strval',$level['user_ids']??[]),true))>{{ $user['label'] }}</option>@endforeach</select></label>@error("levels.$i.user_ids")<span class="error">{{ $message }}</span>@enderror
<label><input style="width:auto" data-field="rejection_comment_required" type="checkbox" name="levels[{{ $i }}][rejection_comment_required]" value="1" @checked($level['rejection_comment_required']??false)> Rejection comment required</label></section>@endforeach
</div>@error('levels')<p class="error">{{ $message }}</p>@enderror
<template id="level-template">@php $i='__INDEX__'; $level=[]; @endphp<section class="card level"><div class="row"><h2>Level <span class="level-number"></span></h2><div><button type="button" class="secondary up">Move up</button> <button type="button" class="secondary down">Move down</button> <button type="button" class="danger remove">Remove</button></div></div><label>Name<input data-field="name" required></label><label>Approver<select data-field="approver_type" class="approver-type"><option value="supervisor">Employee supervisor</option><option value="role">Role</option><option value="users">Selected employees</option></select></label><p class="muted supervisor-help">The applicant's eligible supervisor is resolved when this level is reached.</p><label class="role-field">Role<select data-field="approver_role"><option value="">Select a role</option>@foreach($roles as $role)<option value="{{ $role['value'] }}">{{ $role['label'] }}</option>@endforeach</select></label><label class="users-field">Employees<input class="user-search" type="search" placeholder="Search employees" aria-label="Search employees"><select data-field="user_ids" multiple size="6">@foreach($users as $user)<option value="{{ $user['value'] }}">{{ $user['label'] }}</option>@endforeach</select></label><label><input style="width:auto" data-field="rejection_comment_required" type="checkbox" value="1" checked> Rejection comment required</label></section></template>
<p><button type="button" id="add-level">Add approval level</button> <button type="submit">Save workflow</button></p></form></div>
<script>
(()=>{const box=document.querySelector('#levels'),template=document.querySelector('#level-template'),confirmed=document.querySelector('#confirm-reorder');function refresh(){[...box.children].forEach((el,i)=>{el.dataset.index=i;el.querySelector('.level-number').textContent=i+1;el.querySelectorAll('[data-field]').forEach(x=>x.name=`levels[${i}][${x.dataset.field}]${x.multiple?'[]':''}`);const type=el.querySelector('.approver-type').value;el.querySelector('.role-field').hidden=type!=='role';el.querySelector('.users-field').hidden=type!=='users';el.querySelector('.supervisor-help').hidden=type!=='supervisor';});}box.addEventListener('click',e=>{const el=e.target.closest('.level');if(e.target.matches('.remove')){if(box.children.length===1)return alert('A workflow needs at least one level.');if(confirm('Removing a level changes future routing. Continue?')){el.remove();confirmed.value=1;}}if(e.target.matches('.up')&&el.previousElementSibling&&confirm('Reorder this approval level?')){box.insertBefore(el,el.previousElementSibling);confirmed.value=1;}if(e.target.matches('.down')&&el.nextElementSibling&&confirm('Reorder this approval level?')){box.insertBefore(el.nextElementSibling,el);confirmed.value=1;}refresh();});box.addEventListener('change',e=>{if(e.target.matches('.approver-type'))refresh()});box.addEventListener('input',e=>{if(!e.target.matches('.user-search'))return;const term=e.target.value.toLowerCase(),select=e.target.nextElementSibling;[...select.options].forEach(option=>option.hidden=!option.text.toLowerCase().includes(term));});document.querySelector('#add-level').onclick=()=>{box.append(template.content.cloneNode(true));refresh()};refresh();})();
</script>
